#!/bin/python3

import socket
import sys

HOST = '127.0.0.1'
PORT = 65432

DATA = sys.stdin.read()

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client:
	print(f"[CLIENT] initializing socket; Host:{HOST}, Port:{PORT}")
	client.connect((HOST, PORT))
	print(f"[CLIENT] connected to {HOST}")
	client.sendall(bytes(DATA, 'utf-8'))
	print(f"[CLIENT] data sent, ... closing connection")
